### PR TITLE
WIP Fix/m1 mac

### PR DESCRIPTION
**Pull request by dreaquil**
# Description

- Provide a summary of the modification as well as the issue that has been resolved. List any dependencies that this modification necessitates.

- Fixes # (issue)
- https://github.com/openvinotoolkit/anomalib/issues/150

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by samet-akcay** [comment]
@dreaquil, we'll need to move nncf and openvino related requirements to `requirements/openvino.txt`. 

For the openvino imports in the inferencers, we'll first need to check if openvino is installed before importing the package. Alternatively we could import openvino in the corresponding part of the code rather than at the top of the module. 

For the package version numbers we need some through testing internally to ensure that all the components work fine, and there is no performance degradation in the algorithms. After the check we could use these version numbers.

**Comment by samet-akcay** [comment]
@dreaquil, looks like the branch has conflicts to be solved. If you want to get the pr merged, would you be able to resolve the conflicts please? Thanks

**Comment by dreaquil** [comment]
Hi @samet-akcay! Just checking in that the CI is still broken right?

**Comment by samet-akcay** [comment]
@dreaquil, almost fixed. we'll try to get it up and running before the end of today.

File: anomalib/deploy/inferencers/openvino.py [hunk 1]
```diff
@@ -20,7 +20,8 @@
 import cv2
 import numpy as np
 from omegaconf import DictConfig, ListConfig
-from openvino.inference_engine import IECore  # pylint: disable=no-name-in-module
+
+# from openvino.inference_engine import IECore  # pylint: disable=no-name-in-module
```
Comment (samet-akcay) [inline anomalib/deploy/inferencers/openvino.py:24]: It's unfortunately not possible to comment out this import since openvino stuff depends on this. Perhaps, we could add a check if openvino is installed or not.

File: requirements/base.txt [hunk 2]
```diff
@@ -7,16 +7,17 @@ kornia==0.5.6
 lxml==4.6.5
 matplotlib==3.4.3
 networkx~=2.5
-numpy~=1.19.5
+# nncf==2.1.0
```
Comment (samet-akcay) [inline requirements/base.txt:10]: This line is not needed it was moved to `openvino` requirements now.

Comment (samet-akcay) [inline requirements/base.txt:10]: This line is not needed it was moved to `openvino` requirements now.

File: requirements/base.txt [hunk 3]
```diff
@@ -7,16 +7,17 @@ kornia==0.5.6
...
-torch==1.8.1
-torchvision==0.9.1
-torchtext==0.9.1
+pytorch-lightning==1.6.0
+torch==1.11.0
+torchvision==0.12.0
+torchtext==0.12.0
 scikit-image>=0.17.2
-scikit-learn==0.24.2
+scikit-learn==1.0.2
```
Comment (samet-akcay) [inline requirements/base.txt:22]: it might be an idea to make these dependencies a bit more flexible. Rather than asking for the exact version, we could maybe do something like `scikit-learn>=0.24.2`. In this case would you be able to download the version you want? The reason is that there could be some usecases where another library depends on an earlier package version, but anomalib has the latest version as the dependency, which ultimately would causes hard package dependency conflicts.

Comment (samet-akcay) [inline requirements/base.txt:22]: it might be an idea to make these dependencies a bit more flexible. Rather than asking for the exact version, we could maybe do something like `scikit-learn>=0.24.2`. In this case would you be able to download the version you want? The reason is that there could be some usecases where another library depends on an earlier package version, but anomalib has the latest version as the dependency, which ultimately would causes hard package dependency conflicts.

File: requirements/base.txt [hunk 4]
```diff
@@ -7,16 +7,17 @@ kornia==0.5.6
...
+pandas==1.4.1
 opencv-python>=4.5.3.56
 opencv-contrib-python==4.5.5.62
-pandas~=1.1.5
 pillow==9.0.0
-pytorch-lightning==1.5.9
-torch==1.8.1
-torchvision==0.9.1
-torchtext==0.9.1
+pytorch-lightning==1.6.0
```
Comment (samet-akcay) [inline requirements/base.txt:17]: pytorch-lightning 1.6.0 modified some of the annotations under the hood. CI is failing due to these changes. 
[CI-PR-158.log](https://github.com/openvinotoolkit/anomalib/files/8427463/CI-PR-158.log)

Comment (samet-akcay) [inline requirements/base.txt:17]: pytorch-lightning 1.6.0 modified some of the annotations under the hood. CI is failing due to these changes. 
[CI-PR-158.log](https://github.com/openvinotoolkit/anomalib/files/8427463/CI-PR-158.log)

**Review by samet-akcay — CHANGES_REQUESTED** [review]
@dreaquil, these changes causes the CI to fail due linting and mypy issues. I'll try to check if we could find a common ground to install anomalib on M1 and pass the tests. 

I've attached the CI logs here, showing where/why the CI fails.
[CI-PR-158.log](https://github.com/openvinotoolkit/anomalib/files/8427483/CI-PR-158.log)

File: requirements/base.txt (hunk 4 above)
Comment (dreaquil) [reply requirements/base.txt:16]: This is a problem because I cannot install torchtext 0.9.1 but it does not seem that pytorch lightning 1.5.9 works with 0.12.0.

File: anomalib/deploy/inferencers/openvino.py (hunk 1 above)
Comment (dreaquil) [reply anomalib/deploy/inferencers/openvino.py]: This is no longer an issue on mac.

File: requirements/base.txt (hunk 4 above)
Comment (samet-akcay) [reply requirements/base.txt:16]: can you try the below requirements file to see if it works on you mac?
https://github.com/openvinotoolkit/anomalib/blob/fix/sa/requirements/requirements/base.txt

Comment (samet-akcay) [reply requirements/base.txt:16]: With those requirements, anomalib tests pass. They shoudl be working fine with your mac too.

Comment (dreaquil) [reply requirements/base.txt]: kornia needs to be tied down to 0.5.6 otherwise it throws this error ImportError: cannot import name 'gaussian_blur2d' from 'kornia'

matplotlib seems to be missing from the requirements somehow. I changed my base to match yours and added matplotlib and fixed the kornia dependency.

Comment (samet-akcay) [reply requirements/base.txt]: regarding the kornia, looks like we need to modify the import as follows:

~~from kornia import gaussian_blur2d~~
from kornia.filters import gaussian_blur2d
 in `anomalib/models/patchcore/model.py` and `anomalib/models/padim/model.py`

Comment (dreaquil) [reply requirements/base.txt]: Yep that's right. I also checked that import with the 0.5.6 and it seems to work too. Pushed the change. I can't seem to get the test suite to autodiscover on my machine as it's throwing errors in albumentations but I can give it a try tomorrow. Are tests passing on yours?

Comment (samet-akcay) [reply requirements/base.txt]: When I use the base requirements that I shared with you, tests pass. I used #193 as well, though. I'll be merging it, so you might want to pull the latest develop branch after I merge it. I could trigger your tests afterwards.

Comment (samet-akcay) [reply requirements/base.txt]: Just merged PR #193 now.

Comment (dreaquil) [reply requirements/base.txt]: Merged here.

Comment (samet-akcay) [reply requirements/base.txt]: Thanks, I'll run the CI now.

Comment (samet-akcay) [reply requirements/base.txt]: CI failed due to sorting imports. Can you run 

```
isort  --df anomalib --profile=black
```

from your terminal and push the changes?

Comment (dreaquil) [reply requirements/base.txt]: Ah sorry, left an extra line. Done!

Comment (dreaquil) [reply requirements/base.txt]: @samet-akcay, saw the CI failed. Pushed a fix for tox. Would you mind running the workflow again please?

File: requirements/base.txt [hunk 5]
```diff
@@ -1,21 +1,11 @@
...
 pytorch-lightning>=1.6.0
-torch==1.8.1
-torchvision==0.9.1
-torchtext==0.9.1
-scikit-image>=0.17.2
-scikit-learn==0.24.2
-wandb==0.12.9
+torchvision>=0.9.1
+torchtext>=0.9.1
+wandb>=0.12.9
```
Comment (samet-akcay) [inline requirements/base.txt:10]: @dreaquil, this also needs to be reverted back to `wandb==0.12.9` for now. For some reason, CI fails due to this. We could address it later.

File: requirements/base.txt (hunk 4 above)
Comment (samet-akcay) [reply requirements/base.txt]: @dreaquil, as I mentioned above, if you could set `wandb==0.12.9`, I could re-run the CI, which would hopefully pass this time.

Comment (dreaquil) [reply requirements/base.txt]: Haha, okay... this should be it! @samet-akcay

**Comment by samet-akcay** [comment]
@dreaquil, looks like black also fails. Can you run `black -l 120 anomalib` from your terminal, and hopefully this will be the last change. Thanks :)

if `black` is not installed in your virtualenv, you could run `pip install black`

**Comment by dreaquil** [comment]
> @dreaquil, looks like black also fails. Can you run `black -l 120 anomalib` from your terminal, and hopefully this will be the last change. Thanks :)
> 
> if `black` is not installed in your virtualenv, you could run `pip install black`

Done! here's hoping :)

**Comment by samet-akcay** [comment]
CI has passed finally 🎉. I'm gonna be merging the PR now

**Review by samet-akcay — APPROVED** [review]
